/**
 * @param {Object} param0
 * @param {HTMLDivElement} param0.element
 * @param {any} param0.data
 * @param {string} param0.id
 */
export function init({ element, data, id }) {
	const stored_json = localStorage.getItem("cookies");
	if (!stored_json) {
		element.classList.remove("hidden");
		const accept_all_button = element.querySelector(".accept-all-btn");
		const deny_all_button = element.querySelector(".deny-all-btn");
		const close_button = element.querySelector(".close-btn");
		accept_all_button.addEventListener("click", () => {
			acceptAll();
			element.classList.add("hidden");
		});
		deny_all_button.addEventListener("click", () => {
			denyAll();
			element.classList.add("hidden");
		});
		close_button.addEventListener("click", () => {
			element.classList.add("hidden");
		});
	} else {
		const stored = JSON.parse(stored_json);
		for (const type of stored.allowed) {
			unblockElements(type);
		}
	}
}

function unblockElements(type) {
	if (type === "all") {
		const blocked = document.querySelectorAll("[cookie-banner-blocked]");
		for (const block of blocked) {
			const originalTag = block.getAttribute("data-original-tag");
			const newElement = document.createElement(originalTag);
			for (const attr of block.attributes) {
				newElement.setAttribute(attr.name, attr.value);
			}
			newElement.innerHTML = block.innerHTML;
			// remove the placeholder element, generated by the cookie-banner rewriter
			block.nextElementSibling?.remove();
			block.replaceWith(newElement);
		}
	}
}

function acceptAll() {
	localStorage.setItem(
		"cookies",
		JSON.stringify({
			allowed: ["all"],
		}),
	);
	unblockElements("all");
}
function denyAll() {
	// we can't save anything here, because that would be a cookie and since
	// the user hasn't accepted any cookies, that is not allowed
}
