// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = { message: string, };

export type CookieCategory = { id: number | null, enabled: boolean, label: Record<string, string>, description: Record<string, string>, placeholder_html: string | null, selectors: Array<Selector> | null, };

export type Selector = { id: number | null, selector: string, };

export type Settings = { enabled: boolean, cookie_categories: Array<CookieCategory> | null, };

export type StatusResponse = { success: boolean, };
