/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrayInput: typeof import('./src/components/input/ArrayInput.vue')['default']
    BuilderItemSelectCard: typeof import('./src/components/BuilderItemSelectCard.vue')['default']
    ButtonForm: typeof import('./src/components/element/form/ButtonForm.vue')['default']
    ButtongroupForm: typeof import('./src/components/element/form/ButtongroupForm.vue')['default']
    CheckboxForm: typeof import('./src/components/element/form/CheckboxForm.vue')['default']
    CommonElementForm: typeof import('./src/components/element/form/CommonElementForm.vue')['default']
    DeleteModal: typeof import('./src/components/DeleteModal.vue')['default']
    Element: typeof import('./src/components/element/Element.vue')['default']
    ElementForm: typeof import('./src/components/ElementForm.vue')['default']
    EmailForm: typeof import('./src/components/EmailForm.vue')['default']
    FormBuilder: typeof import('./src/components/FormBuilder.vue')['default']
    FormForm: typeof import('./src/components/FormForm.vue')['default']
    FormLink: typeof import('./src/components/FormLink.vue')['default']
    FormPreview: typeof import('./src/components/FormPreview.vue')['default']
    InfoPopover: typeof import('./src/components/InfoPopover.vue')['default']
    LocalizedTextInput: typeof import('./src/components/input/LocalizedTextInput.vue')['default']
    ModalSaveButtons: typeof import('./src/components/ModalSaveButtons.vue')['default']
    NumberForm: typeof import('./src/components/element/form/NumberForm.vue')['default']
    RangeForm: typeof import('./src/components/element/form/RangeForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectForm: typeof import('./src/components/element/form/SelectForm.vue')['default']
    SendEmailModal: typeof import('./src/components/SendEmailModal.vue')['default']
    TextareaForm: typeof import('./src/components/element/form/TextareaForm.vue')['default']
    TextForm: typeof import('./src/components/element/form/TextForm.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UButtonGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UCollapsible: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    ULinkBase: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
